name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build and tag Docker images for both containers
      - name: Build and tag Docker images
        run: |
          IMAGE_TAG=${{ github.sha }}

          # Build the app (expenses-tracker) container
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/expenses-tracker:$IMAGE_TAG .
          docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/expenses-tracker:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/expenses-tracker:latest

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Step 6: Push Docker images to Amazon ECR
      - name: Push Docker images to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/expenses-tracker:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/expenses-tracker:latest

      # Step 7: Update ECS task definition and replace image URI in ecs/task-def.json
      - name: Update ECS task definition
        run: |
          # Replace the image URI with the new image tag in ecs/task-def.json
          sed -i 's|442474044593.dkr.ecr.us-east-1.amazonaws.com/expenses-tracker:latest|${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/expenses-tracker:${{ github.sha }}|' ecs/task-def.json

      # Step 8: Register updated ECS task definition
      - name: Register ECS task definition
        run: |
          aws ecs register-task-definition --cli-input-json file://ecs/task-def.json

      # Step 9: Deploy ECS service
      - name: Deploy ECS service
        run: |
          aws ecs update-service --cluster expenses-tracker-cluster-2 --service expenses-tracker-service --force-new-deployment
